### ISSUE TITLE
README中示例用法疑似有误

### ISSUE THREAD

**Issue by liulyxandy-codemao** [lc-cn/onebot-client#1]
[此处示例](https://github.com/lc-cn/onebot-client#1-linkserver)
1. `clent.start.then(()=>{` 应作 `client.start().then(()=>{`
2. 
```js
logger.notice('正在登录...')
client.start().then((x)=>{
    logger.notice('协议启动成功')
})
```
控制台显示：
`
NOTICE 正在登录...
`
随后直接退出了程序

修改代码为以下方法：
```js
logger.notice('正在登录...');
(async ()=>{
    client.start()
    logger.notice('协议启动成功')
})()
```
代码正常运行

**Comment by lc-cn** [comment]
啊？这个还有人用？那你提个pr 吧

**Comment by lc-cn** [comment]
该错误我已修正，是代码问题
